import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { supabase } from '../../lib/supabase';
import { LanguageCode, UserProfile, UserRole } from '../../types';
import { setAppLanguage } from '../../i18n';
import { useAppStore } from '../../stores/useAppStore';
import { SignUpFormData } from './schemas';

interface AuthContextType { currentUser: User | null; profile: UserProfile | null; loading: boolean; isSubmitting: boolean; isAuthenticated: boolean; role: UserRole; authError: string | null; isOperationNotAllowed: boolean; login: (email:string,password:string)=>Promise<any>; signInWithGoogle:()=>Promise<any>; signup:(data:SignUpFormData)=>Promise<any>; logout:()=>Promise<void>; resetPassword:(email:string)=>Promise<any>; updateProfile:(updates:Partial<UserProfile>)=>Promise<any>; clearAuthError:()=>void; }
const AuthContext = createContext<AuthContextType | undefined>(undefined);
const allowed: UserRole[] = ['CUSTOMER','PROVIDER','ADMIN','OPS_ADMIN','FINANCE_ADMIN','SUPER_ADMIN'];
const lang = () => (localStorage.getItem('rsc_preferred_lang') as LanguageCode) || 'en';
const message = (error?: any) => error?.message?.includes('Invalid login credentials') ? 'Email or password is incorrect.' : error?.message || 'Something went wrong. Please try again.';

export const AuthProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
 const [currentUser,setCurrentUser]=useState<User|null>(null),[profile,setProfile]=useState<UserProfile|null>(null),[role,setRole]=useState<UserRole>('CUSTOMER'),[loading,setLoading]=useState(true),[isSubmitting,setIsSubmitting]=useState(false),[authError,setAuthError]=useState<string|null>(null);
 const {setCity,setLanguage:setStoreLanguage,setRole:setStoreRole}=useAppStore(); const clearAuthError=useCallback(()=>setAuthError(null),[]);
 const load=useCallback(async(user:User)=>{const candidate=user.app_metadata?.role;const userRole=typeof candidate==='string'&&allowed.includes(candidate as UserRole)?candidate as UserRole:'CUSTOMER';const {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;const fallback:UserProfile={uid:user.id,id:user.id,authUserId:user.id,fullName:typeof user.user_metadata?.full_name==='string'?user.user_metadata.full_name:user.email?.split('@')[0]||'User',email:user.email||'',phone:'',cityId:'city-ras-gharib',preferredLanguage:lang(),role:userRole,isActive:true,termsAccepted:false,termsAcceptedAt:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return {profile:{...fallback,...(data||{}),uid:user.id,id:user.id,authUserId:user.id,email:user.email||''} as UserProfile,role:userRole};},[]);
 const apply=useCallback((next:UserProfile,userRole:UserRole)=>{setProfile(next);setRole(userRole);setStoreRole(userRole);setCity(next.cityId);setAppLanguage(next.preferredLanguage);setStoreLanguage(next.preferredLanguage);},[setCity,setStoreLanguage,setStoreRole]);
 useEffect(()=>{let active=true;const hydrate=async(user:User|null)=>{if(!active)return;setCurrentUser(user);if(!user){setProfile(null);setRole('CUSTOMER');setStoreRole('CUSTOMER');setLoading(false);return;}try{const loaded=await load(user);if(active)apply(loaded.profile,loaded.role);}catch(e){if(active)setAuthError(message(e));}finally{if(active)setLoading(false);}};supabase.auth.getSession().then(({data})=>hydrate(data.session?.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>hydrate(session?.user??null));return()=>{active=false;subscription.unsubscribe();};},[apply,load,setStoreRole]);
 const fail=(e:any)=>{const text=message(e);setAuthError(text);return {success:false,error:text};}; const resolve=async(user:User)=>{const loaded=await load(user);apply(loaded.profile,loaded.role);return loaded.role;};
 const login=async(email:string,password:string)=>{setIsSubmitting(true);clearAuthError();try{const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});return error||!data.user?fail(error):{success:true,role:await resolve(data.user)};}catch(e){return fail(e);}finally{setIsSubmitting(false);}};
 const signInWithGoogle=async()=>{setIsSubmitting(true);clearAuthError();try{const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});return error?fail(error):{success:true,role:'CUSTOMER'};}catch(e){return fail(e);}finally{setIsSubmitting(false);}};
 const signup=async(data:SignUpFormData)=>{setIsSubmitting(true);clearAuthError();try{const response=await supabase.auth.signUp({email:data.email.trim(),password:data.password,options:{emailRedirectTo:window.location.origin,data:{full_name:data.fullName.trim()}}});if(response.error)return fail(response.error);if(response.data.user&&response.data.session){const now=new Date().toISOString();const next:UserProfile={uid:response.data.user.id,id:response.data.user.id,authUserId:response.data.user.id,fullName:data.fullName.trim(),email:data.email.trim(),phone:data.phone.trim(),cityId:data.cityId,preferredLanguage:data.preferredLanguage,role:'CUSTOMER',isActive:true,termsAccepted:true,termsAcceptedAt:now,createdAt:now,updatedAt:now};const {error}=await supabase.from('profiles').upsert({...next,id:response.data.user.id});if(error)return fail(error);apply(next,'CUSTOMER');}return {success:true};}catch(e){return fail(e);}finally{setIsSubmitting(false);}};
 const resetPassword=async(email:string)=>{setIsSubmitting(true);clearAuthError();try{const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/login`});return error?fail(error):{success:true};}catch(e){return fail(e);}finally{setIsSubmitting(false);}};
 const logout=async()=>{await supabase.auth.signOut();setCurrentUser(null);setProfile(null);setRole('CUSTOMER');setStoreRole('CUSTOMER');};
 const updateProfile=async(updates:Partial<UserProfile>)=>{if(!currentUser||!profile)return fail({message:'You must be signed in to update your profile.'});setIsSubmitting(true);try{const safe={fullName:updates.fullName?.trim(),phone:updates.phone?.trim(),cityId:updates.cityId,addressText:updates.addressText?.trim(),preferredLanguage:updates.preferredLanguage,updatedAt:new Date().toISOString()};const {error}=await supabase.from('profiles').update(safe).eq('id',currentUser.id);if(error)return fail(error);if(safe.fullName)await supabase.auth.updateUser({data:{full_name:safe.fullName}});apply({...profile,...safe} as UserProfile,role);return {success:true};}catch(e){return fail(e);}finally{setIsSubmitting(false);}};
 const value=useMemo<AuthContextType>(()=>({currentUser,profile,loading,isSubmitting,isAuthenticated:Boolean(currentUser),role,authError,isOperationNotAllowed:false,login,signInWithGoogle,signup,logout,resetPassword,updateProfile,clearAuthError}),[currentUser,profile,loading,isSubmitting,role,authError,clearAuthError]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}; export const useAuth=()=>{const context=useContext(AuthContext);if(!context)throw new Error('useAuth must be used within an AuthProvider');return context;};
